function getExportThemeToken(aliasToken, sceneToken, colorSet, colorBoard, themeName) {
    const {
        colorTextPrimary,
        colorTextPlaceholder,
      } = sceneToken
      const {
        colorBgContainer,
        colorBgContainerSecondary,
        colorBgContainerHover,
        colorIcon,
        colorPlaceholder,
        colorAxisLine,
        colorIconInactive,
        colorAxisPointerLine,
        colorShadowHover,
        colorShadowContainer,
        colorZoomHandle,
        colorShadowHandle,
        colorZoomBg,
        colorZoomDataAreaBorder,
        colorZoomSelectDataAreaFill,
        colorZoomSelectDataAreaBorder,

      } = aliasToken;
    return {
        "ti-color-chart-1": colorSet.colorGroup[0],
        "ti-color-chart-2": colorSet.colorGroup[1],
        "ti-color-chart-3": colorSet.colorGroup[2],
        "ti-color-chart-4": colorSet.colorGroup[3],
        "ti-color-chart-5": colorSet.colorGroup[4],
        "ti-color-chart-6": colorSet.colorGroup[5],
        "ti-color-chart-7": colorSet.colorGroup[6],
        "ti-color-chart-8": colorSet.colorGroup[7],
        "ti-color-chart-9": colorBoard.gray.colorGray50,
        "ti-color-chart-10": colorSet.colorGroup[8],
        "ti-color-chart-11": colorSet.colorGroup[9],
        "ti-color-chart-12": colorSet.colorGroup[10],
        "ti-color-chart-13": colorSet.colorGroup[11],
        "ti-color-chart-14": colorSet.colorGroup[12],
        "ti-color-chart-15": colorSet.colorGroup[13],
        "ti-color-chart-16": colorSet.colorGroup[14],
        "ti-color-chart-17": colorSet.colorGroup[15],
        "ti-color-chart-18": colorSet.colorGroup[16],
        "ti-color-chart-19": colorSet.colorGroup[17],
        "ti-color-chart-20": colorSet.colorGroup[18],
        "ti-color-chart-21": colorSet.colorGroup[19],
        "ti-color-chart-22": colorSet.colorGroup[20],
        "ti-color-chart-23": colorSet.colorGroup[21],
        "ti-color-chart-24": colorSet.colorGroup[22],
        "ti-color-chart-25": colorSet.colorGroup[23],
        "ti-color-chart-26": colorSet.colorGroup[24],
        "ti-color-text-error": colorSet.colorState.colorError,
        "ti-color-text-warning": colorSet.colorState.colorAlert,
        "ti-color-text-secondary": colorSet.colorState.colorWarning,
        "ti-color-text-success": colorSet.colorState.colorSuccess,
        "ti-color-text-info": colorSet.colorState.colorInfo,
        "ti-color-text-disabled": colorSet.colorState.colorNone,
        "ti-color-text-primary": colorTextPrimary,
        "ti-color-text-placeholder": colorTextPlaceholder,
        "ti-color-alarm-fatal": colorSet.colorAlarms.colorAlarmFatal,
        "ti-color-alarm-error": colorSet.colorAlarms.colorAlarmError,
        "ti-color-alarm-warning": colorSet.colorAlarms.colorAlarmWarning,
        "ti-color-alarm-secondary": colorSet.colorAlarms.colorAlarmSecondary,
        "ti-color-alarm-ordinary": colorSet.colorAlarms.colorAlarmOrdinary,
        "ti-color-icon-default": colorIcon,
        "ti-color-icon-disabled": colorIconInactive,
        "ti-color-icon-hover": colorTextPrimary,
        "ti-color-icon-active": colorTextPrimary,
        "ti-color-bg-container-secondary": colorBgContainer,
        "ti-color-bg-overlay-default": colorBgContainerSecondary,
        "ti-color-bg-active": colorBgContainerHover,
        "ti-color-bg-tag-gray": colorPlaceholder,
        "ti-color-bg-default": colorShadowHover,
        "ti-color-border-chart-divider": colorAxisLine,
        "ti-color-border-hover": colorAxisPointerLine,
        "ti-color-bg-control-active": colorZoomSelectDataAreaBorder,
        "ti-color-bg-control-disable-2": colorZoomSelectDataAreaFill,
        "ti-color-border-default": colorZoomDataAreaBorder,
        "ti-color-border-container-active": colorZoomSelectDataAreaBorder,
        "ti-color-icon-inverse": colorZoomHandle,
        "ti-shadow-m-down": `0 2px 12px 0 ${colorShadowContainer}`,
        "ti-shadow-s-down": themeName.includes('light') ? `0 1px 4px 0 ${colorShadowHandle}` : `0 2px 12px 0 ${colorShadowHandle}`

    }
}

export default getExportThemeToken

