name: Deploy to github.io

on:
  push:
    branches: [dev]

  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install deps
        run: npm install --unsafe-perm=true --allow-root --legacy-peer-deps
      - name: Build doc
        run: npm run build:opentiny
        env:
          VITE_BASEROUTER: tiny-charts
          VITE_PUBLISH_URL: /tiny-charts/
      - name: Copy files
        run: |
          cp dist/index.html dist/404.html
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./dist
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
